/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticalChart: typeof import('./src/components/Teachers/AnalyticalChart.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AttendanceChart: typeof import('./src/components/Admin/AttendanceChart.vue')['default']
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    DefaultQRCode: typeof import('./src/components/QRCodes/DefaultQRCode.vue')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FilteringTable: typeof import('./src/components/dashboard/FilteringTable.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    NextClassNotification: typeof import('./src/components/Teachers/NextClassNotification.vue')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    QRScanner: typeof import('./src/components/dashboard/QRScanner.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SakaiCard: typeof import('./src/components/SakaiCard.vue')['default']
    SearchStudentId: typeof import('./src/components/dashboard/SearchStudentId.vue')['default']
    StatsWidget: typeof import('./src/components/Teachers/StatsWidget.vue')['default']
    TopAbsentees: typeof import('./src/components/Teachers/TopAbsentees.vue')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
  }
}
